# ------------------------------------------------------------
# Jump ACI
# ------------------------------------------------------------
module "jump_aci" {
  source = "../modules/jump-aci"

  location            = var.location
  resource_group_name = module.governance.platform_resource_group_name
  subnet_id           = module.hub_network.subnet_ids["aci"]

  container_name  = "jump-aci"
  #container_image = "mcr.microsoft.com/azure-cli:2.52.0"
  #container_image = "platformregistryjames.azurecr.io/jump-aci:latest"
  container_image = "ghcr.io/jalcock-training/jump-aci:latest"


  cpu_cores       = 1
  memory_gb       = 1

  # Pass private key securely into ACI
  private_key_openssh = tls_private_key.jump.private_key_openssh
  vm_name         = module.jumphost_vm.vm_name

  tags = {
    Environment = "dev"
    Owner       = "James"
    Project     = "AzureHybridLandingZone"
  }
}

# ------------------------------------------------------------
# Jumphost VM 
# ------------------------------------------------------------
module "jumphost_vm" {
  source = "../modules/jumphost-vm"

  location            = var.location
  resource_group_name = module.governance.platform_resource_group_name
  subnet_id           = module.hub_network.subnet_ids["jumphost"]
  subscription_id = var.subscription_id

  admin_username = "azureuser"
  # Inject public key generated by Terraform
  ssh_public_key  = tls_private_key.jump.public_key_openssh
  ssh_private_key = tls_private_key.jump.private_key_pem

  vm_size = "Standard_D2as_v5"

  tags = {
    Environment = "dev"
    Owner       = "James"
    Project     = "AzureHybridLandingZone"
  }
}

# For access to tfstate so jumphost vm can be run terraform using delegated identity

data "azurerm_storage_account" "tfstate" {
  name                = var.tfstate_storage_account_name
  resource_group_name = var.tfstate_resource_group_name
}

data "azurerm_subscription" "current" {}

resource "azurerm_role_assignment" "jumphost_tfstate_access" {
  scope                = data.azurerm_storage_account.tfstate.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = module.jumphost_vm.identity_principal_id
}

# ------------------------------------------------------------
# Generate SSH keypair for ACI → VM access
# ------------------------------------------------------------
resource "tls_private_key" "jump" {
  algorithm = "RSA"
  rsa_bits  = 4096
  ecdsa_curve = null
}

# ------------------------------------------------------------
# RBAC: Allow ACI to start/stop the VM
# ------------------------------------------------------------
resource "azurerm_role_assignment" "aci_vm_control" {
  scope                = module.jumphost_vm.vm_id
  role_definition_name = "Virtual Machine Contributor"
  principal_id         = module.jump_aci.identity_principal_id
}

# ------------------------------------------------------------
# RBAC: Allow jumphost to manage key vault objects
# ------------------------------------------------------------

resource "azurerm_role_assignment" "jumphost_kv_cert_officer" {
  scope                = module.shared_services.key_vault_id
  role_definition_name = "Key Vault Certificates Officer"
  principal_id         = module.jumphost_vm.identity_principal_id
}

resource "azurerm_role_assignment" "jumphost_kv_secrets_officer" {
  scope                = module.shared_services.key_vault_id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = module.jumphost_vm.identity_principal_id
}

