# ------------------------------------------------------------
# Workload VM Module
# Deploys an Ubuntu VM running NGINX over HTTPS using:
# - System-assigned managed identity
# - Certificate generated by Terraform
# - Certificate stored in Key Vault
# - Static content downloaded from Storage at boot
# ------------------------------------------------------------

locals {
  tags = var.common_tags

  certificate_subject = "${var.name_prefix}-workload.internal"

  cloud_init = templatefile("${path.module}/cloud-init-workload.yaml", {
    storage_account_id     = data.azurerm_storage_account.sa.id
    storage_container_name = azurerm_storage_container.workload_content.name
    kv_name                = data.azurerm_key_vault.kv.name
    kv_cert_name           = azurerm_key_vault_certificate.workload_cert.name
  })
}

# ------------------------------------------------------------
# Data Sources
# ------------------------------------------------------------

data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

data "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azapi_resource" "workload_subnet" {
  type        = "Microsoft.Network/virtualNetworks/subnets@2023-05-01"
  resource_id = var.workload_subnet_id
}

data "azurerm_key_vault" "kv" {
  name                = var.kv_name
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azurerm_subscription" "current" {}

data "azurerm_storage_account" "sa" {
  name                = var.storage_account_name
  resource_group_name = data.azurerm_resource_group.rg.name
}


# ------------------------------------------------------------
# Certificate Generation (Terraform → Key Vault)
# ------------------------------------------------------------

resource "tls_private_key" "workload_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "workload_cert" {
  private_key_pem = tls_private_key.workload_key.private_key_pem

  subject {
    common_name  = local.certificate_subject
    organization = "James Training Workload"
  }

  validity_period_hours = 8760 # 1 year
  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "azurerm_key_vault_certificate" "workload_cert" {
  name         = "${var.name_prefix}-workload-cert"
  key_vault_id = data.azurerm_key_vault.kv.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pem-file"
    }

    x509_certificate_properties {
      subject            = "CN=${local.certificate_subject}"
      validity_in_months = 12

      extended_key_usage = ["1.3.6.1.5.5.7.3.1"] # serverAuth
      key_usage = [
        "digitalSignature",
        "keyEncipherment"
      ]
    }
  }
}

# ------------------------------------------------------------
# Network Interface
# ------------------------------------------------------------

resource "azurerm_network_interface" "nic" {
  name                = "${var.name_prefix}-workload-nic"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = data.azapi_resource.workload_subnet.id
    private_ip_address_allocation = "Dynamic"
  }

  tags = local.tags
}

# ------------------------------------------------------------
# Virtual Machine
# ------------------------------------------------------------

resource "azurerm_linux_virtual_machine" "vm" {
  name                = "${var.name_prefix}-workload-vm"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.rg.name
  size                = var.vm_size

  admin_username = var.vm_admin_username

  network_interface_ids = [
    azurerm_network_interface.nic.id
  ]

  admin_ssh_key {
    username   = var.vm_admin_username
    public_key = var.vm_ssh_public_key
  }

  disable_password_authentication = true

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  custom_data = base64encode(local.cloud_init)

  tags = local.tags
}

# ------------------------------------------------------------
# Access Policies
# ------------------------------------------------------------

resource "azurerm_key_vault_access_policy" "vm_kv_access" {
  key_vault_id = data.azurerm_key_vault.kv.id

  tenant_id = data.azurerm_subscription.current.tenant_id
  object_id = azurerm_linux_virtual_machine.vm.identity[0].principal_id

  certificate_permissions = ["Get", "List"]
  secret_permissions      = ["Get", "List"]
}

resource "azurerm_role_assignment" "vm_storage_reader" {
  scope                = data.azurerm_storage_account.sa.id
  role_definition_name = "Storage Blob Data Reader"
  principal_id         = azurerm_linux_virtual_machine.vm.identity[0].principal_id
}

# ------------------------------------------------------------
# Storage Container for Workload Content
# ------------------------------------------------------------

resource "azurerm_storage_container" "workload_content" {
  name                  = "${var.name_prefix}-workload-content"
  storage_account_id    = data.azurerm_storage_account.sa.id
  container_access_type = "private"
}

