# ------------------------------------------------------------
# Workload VM Module
# Deploys an Ubuntu VM running NGINX over HTTPS using:
# - System-assigned managed identity
# - Certificate generated by Terraform
# - Certificate stored in Key Vault
# - Static content downloaded from Storage at boot
# ------------------------------------------------------------

locals {
  tags = var.common_tags

  certificate_subject = "${var.name_prefix}-workload.internal"
}

# ------------------------------------------------------------
# Data Sources
# ------------------------------------------------------------

data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

data "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azurerm_subnet" "workload" {
  name                 = var.workload_subnet_name
  virtual_network_name = data.azurerm_virtual_network.vnet.name
  resource_group_name  = data.azurerm_resource_group.rg.name
}

data "azurerm_key_vault" "kv" {
  name                = var.kv_name
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azurerm_storage_account" "sa" {
  name                = var.storage_account_name
  resource_group_name = data.azurerm_resource_group.rg.name
}

data "azurerm_subscription" "current" {}

# ------------------------------------------------------------
# Certificate Generation (Terraform → Key Vault)
# ------------------------------------------------------------

resource "tls_private_key" "workload_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "workload_cert" {
  private_key_pem = tls_private_key.workload_key.private_key_pem

  subject {
    common_name  = local.certificate_subject
    organization = "James Training Workload"
  }

  validity_period_hours = 8760 # 1 year
  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "azurerm_key_vault_certificate" "workload_cert" {
  name         = "${var.name_prefix}-workload-cert"
  key_vault_id = data.azurerm_key_vault.kv.id

  certificate {
    contents = tls_self_signed_cert.workload_cert.cert_pem
  }

  key_properties {
    exportable = true
    key_size   = 2048
    key_type   = "RSA"
    reuse_key  = false
  }

  secret_properties {
    content_type = "application/x-pem-file"
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ------------------------------------------------------------
# Network Security Group
# ------------------------------------------------------------

resource "azurerm_network_security_group" "workload_nsg" {
  name                = "${var.name_prefix}-workload-nsg"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.rg.name

  security_rule {
    name                       = "Allow-SSH-from-Jumphost"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefixes    = var.jumphost_cidrs
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "Allow-HTTPS-Internal"
    priority                   = 200
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "443"
    source_address_prefixes    = var.internal_cidrs
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "Deny-All-Inbound"
    priority                   = 4000
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }

  tags = local.tags
}

resource "azurerm_subnet_network_security_group_association" "workload_nsg_assoc" {
  subnet_id                 = data.azurerm_subnet.workload.id
  network_security_group_id = azurerm_network_security_group.workload_nsg.id
}

# ------------------------------------------------------------
# Network Interface
# ------------------------------------------------------------

resource "azurerm_network_interface" "nic" {
  name                = "${var.name_prefix}-workload-nic"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = data.azurerm_subnet.workload.id
    private_ip_address_allocation = "Dynamic"
  }

  tags = local.tags
}

# ------------------------------------------------------------
# Cloud-init Template
# ------------------------------------------------------------

data "templatefile" "cloud_init" {
  template = file("${path.module}/cloud-init-workload.yaml")

  vars = {
    storage_account_name   = data.azurerm_storage_account.sa.name
    storage_container_name = var.storage_container_name
    kv_name                = data.azurerm_key_vault.kv.name
    kv_cert_name           = azurerm_key_vault_certificate.workload_cert.name
  }
}

# ------------------------------------------------------------
# Virtual Machine
# ------------------------------------------------------------

resource "azurerm_linux_virtual_machine" "vm" {
  name                = "${var.name_prefix}-workload-vm"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.rg.name
  size                = var.vm_size

  admin_username = var.vm_admin_username

  network_interface_ids = [
    azurerm_network_interface.nic.id
  ]

  admin_ssh_key {
    username   = var.vm_admin_username
    public_key = var.vm_ssh_public_key
  }

  disable_password_authentication = true

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  custom_data = base64encode(data.templatefile.cloud_init.rendered)

  tags = local.tags
}

# ------------------------------------------------------------
# Access Policies
# ------------------------------------------------------------

resource "azurerm_key_vault_access_policy" "vm_kv_access" {
  key_vault_id = data.azurerm_key_vault.kv.id

  tenant_id = data.azurerm_subscription.current.tenant_id
  object_id = azurerm_linux_virtual_machine.vm.identity[0].principal_id

  certificate_permissions = ["Get", "List"]
  secret_permissions      = ["Get", "List"]
}

resource "azurerm_role_assignment" "vm_storage_reader" {
  scope                = data.azurerm_storage_account.sa.id
  role_definition_name = "Storage Blob Data Reader"
  principal_id         = azurerm_linux_virtual_machine.vm.identity[0].principal_id
}

