# ------------------------------------------------------------
# Workload VM Module
# Deploys an Ubuntu VM running NGINX over HTTPS using:
# - System-assigned managed identity
# - Certificate generated by Terraform
# - Certificate stored in Key Vault
# - Static content downloaded from Storage at boot
# ------------------------------------------------------------

locals {
  tags = var.tags

  certificate_subject = "${var.name_prefix}-workload.internal"

  cloud_init = templatefile("${path.module}/cloud-init-workload.yaml", {
    storage_account_name   = data.azurerm_storage_account.sa.name
    storage_container_name = azurerm_storage_container.workload_content.name
    kv_name                = data.azurerm_key_vault.kv.name
    kv_cert_name           = azurerm_key_vault_certificate.workload_cert.name
  })
}

# ------------------------------------------------------------
# Data Sources
# ------------------------------------------------------------

data "azapi_resource" "workload_subnet" {
  type        = "Microsoft.Network/virtualNetworks/subnets@2023-05-01"
  resource_id = var.workload_subnet_id
}

data "azurerm_key_vault" "kv" {
  name                = var.kv_name
  resource_group_name = var.key_vault_resource_group_name
}

data "azurerm_subscription" "current" {}

data "azurerm_storage_account" "sa" {
  name                = var.storage_account_name
  resource_group_name = var.storage_resource_group_name
}

/*
# ------------------------------------------------------------
# Certificate Generation (Terraform → Key Vault)
# ------------------------------------------------------------

resource "tls_private_key" "workload_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "workload_cert" {
  private_key_pem = tls_private_key.workload_key.private_key_pem

  subject {
    common_name = local.certificate_subject
  }

  validity_period_hours = 8760
  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "pkcs12_certificate" "workload_pfx" {
  private_key_pem = tls_private_key.workload_key.private_key_pem
  certificate_pem = tls_self_signed_cert.workload_cert.cert_pem
  password        = ""
}

resource "azurerm_key_vault_certificate" "workload_cert" {
  name         = "${var.name_prefix}-workload-cert"
  key_vault_id = data.azurerm_key_vault.kv.id

  certificate {
    contents = pkcs12_certificate.workload_pfx.pfx_base64
  }
}


# ------------------------------------------------------------
# Network Interface
# ------------------------------------------------------------

resource "azurerm_network_interface" "nic" {
  name                = "${var.name_prefix}-workload-nic"
  location            = var.location
  resource_group_name = var.resource_group_name

  ip_configuration {
    name                          = "ipconfig1"
    subnet_id                     = data.azapi_resource.workload_subnet.id
    private_ip_address_allocation = "Dynamic"
  }

  tags = local.tags
}

# ------------------------------------------------------------
# Virtual Machine
# ------------------------------------------------------------

resource "azurerm_linux_virtual_machine" "workload" {
  name                = "${var.name_prefix}-workload"
  location            = var.location
  resource_group_name = var.resource_group_name
  size                = var.workload_size

  admin_username = var.jumphost_admin_username

  network_interface_ids = [
    azurerm_network_interface.nic.id
  ]

  admin_ssh_key {
    username   = var.jumphost_admin_username
    public_key = var.jumphost_ssh_public_key
  }

  disable_password_authentication = true

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  custom_data = base64encode(local.cloud_init)

  tags = local.tags
}

# ------------------------------------------------------------
# RBAC: Allow storage access 
# ------------------------------------------------------------

resource "azurerm_role_assignment" "workload_storage_reader" {
  scope                = data.azurerm_storage_account.sa.id
  role_definition_name = "Storage Blob Data Reader"
  principal_id         = azurerm_linux_virtual_machine.workload.identity[0].principal_id
}

# ------------------------------------------------------------
# Storage Container for Workload Content
# ------------------------------------------------------------

resource "azurerm_storage_container" "workload_content" {
  name                  = "${var.name_prefix}-workload-content"
  storage_account_id    = data.azurerm_storage_account.sa.id
  container_access_type = "private"
}

# ------------------------------------------------------------
# RBAC: Allow workload VM access to the key vault
# ------------------------------------------------------------

resource "azurerm_role_assignment" "workload_kv_cert_officer" {
  scope                = var.key_vault_id
  role_definition_name = "Key Vault Certificates Officer"
  principal_id         = azurerm_linux_virtual_machine.workload.identity[0].principal_id
}

resource "azurerm_role_assignment" "workload_kv_secrets_officer" {
  scope                = var.key_vault_id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = azurerm_linux_virtual_machine.workload.identity[0].principal_id
}

# ------------------------------------------------------------
# Create the blob storage index.html file
# ------------------------------------------------------------

resource "azurerm_storage_blob" "workload_index_html" {
  name                   = "index.html"
  storage_account_name   = var.storage_account_name
  storage_container_name = azurerm_storage_container.workload_content.name
  type                   = "Block"
  source_content         = <<EOF
<!DOCTYPE html>
<html>
<head>
  <title>James' Training Workload</title>
</head>
<body>
  <h1>Hello from Terraform‑managed content</h1>
  <p>This file was uploaded automatically by the workload module.</p>
</body>
</html>
EOF
}

