# ------------------------------------------------------------
# Jump ACI
# ------------------------------------------------------------
module "jump_aci" {
  source = "./modules/jump-aci"

  location            = var.location
  resource_group_name = module.governance.platform_resource_group_name
  subnet_id           = module.hub_network.subnet_ids["aci"]

  container_name  = "jump-aci"
  container_image = "mcr.microsoft.com/azure-cli:2.52.0"
  cpu_cores       = 1
  memory_gb       = 1

  # Pass private key securely into ACI
  private_key_pem = tls_private_key.jump.private_key_pem
  vm_name         = module.jumphost_vm.vm_name

  tags = {
    Environment = "dev"
    Owner       = "James"
    Project     = "AzureHybridLandingZone"
  }
}

# ------------------------------------------------------------
# Jumphost VM 
# ------------------------------------------------------------
module "jumphost_vm" {
  source = "./modules/jumphost-vm"

  location            = var.location
  resource_group_name = module.governance.platform_resource_group_name
  subnet_id           = module.hub_network.subnet_ids["shared_services"]

  admin_username = "azureuser"
  # Inject public key generated by Terraform
  ssh_public_key  = tls_private_key.jump.public_key_openssh
  ssh_private_key = tls_private_key.jump.private_key_pem

  vm_size = "Standard_D2as_v5"

  tags = {
    Environment = "dev"
    Owner       = "James"
    Project     = "AzureHybridLandingZone"
  }
}

# ------------------------------------------------------------
# Generate SSH keypair for ACI → VM access
# ------------------------------------------------------------
resource "tls_private_key" "jump" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# ------------------------------------------------------------
# RBAC: Allow ACI to start/stop the VM
# ------------------------------------------------------------
resource "azurerm_role_assignment" "aci_vm_control" {
  scope                = module.jumphost_vm.vm_id
  role_definition_name = "Virtual Machine Contributor"
  principal_id         = module.jump_aci.identity_principal_id
}
